name = "SymPy"
uuid = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
version = "2.0.0"

[deps]
CommonEq = "3709ef60-1bee-4518-9f2f-acd86f176c50"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SymPyCore = "458b697b-88f0-4a86-b56b-78b75cfb3531"

[compat]
CommonEq = "0.2.1"
CommonSolve = "0.2"
LinearAlgebra = "<0.0.1, 1.6"
PyCall = "1.96"
SpecialFunctions = "0.7, 0.8, 0.8, 0.10, 1, 2"
SymbolicUtils = "1"
SymPyCore = "0.1.6, 1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[targets]
test = ["Test", "LinearAlgebra", "SpecialFunctions", "SymbolicUtils"]
